package io.github.fierg.model.options

enum class ENV {
    THRESHOLD,
    DECOMPOSITION_MODE,
    COMPOSITION_MODE,
    FULL_LENGTH_DECOMPOSITION,
    DELTA_WINDOW_PREPROCESSING,
    DELTA_WINDOW_ALGO,
    SKIP_SINGLE_STEP_EDGES,
    DEBUG,
    QUIET,
}