# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Latex Document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build tex from bash
        uses: dante-ev/latex-action@latest
        with:
          working_directory: thesis
          entrypoint: ./tex-build.sh

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: thesis/thesis.pdf